apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base

replicas:
  - name: frontend
    count: 2
  - name: bff
    count: 2
  - name: user-service
    count: 2
  - name: message-service
    count: 2

images:
  - name: mablinov2704/frontend
    newTag: v1.0.0
  - name: mablinov2704/bff
    newTag: v1.0.0
  - name: mablinov2704/user-service
    newTag: v1.0.0
  - name: mablinov2704/message-service
    newTag: v1.0.0

patches:
  - path: patch-resources.yaml