apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: messager

resources:
  - namespace.yaml
  - configmap.yaml
  - secret.yaml
  - postgres-pvc.yaml
  - postgres.yaml
  - migrate-users-job.yaml
  - migrate-messages-job.yaml
  - user-service.yaml
  - bff.yaml
  - frontend.yaml
  - minio-secret.yaml
  - minio.yaml
  - s3-pvc.yaml
  - message-service.yaml

configMapGenerator:
  - name: users-migrations-cm
    files:
      - user-migrations/001_init.sql
  - name: messages-migrations-cm
    files:
      - message-migrations/001_init.sql
      - message-migrations/002_add_file_name.sql
  - name: postgres-init-cm
    files:
      - init-db.sh