apiVersion: v1
kind: Secret
metadata:
  name: minio-secret
  namespace: messager
stringData:
  accessKeyID: messager-key
  secretAccessKey: messager-secret-key
  endpoint: http://minio.messager.svc.cluster.local:9000
type: Opaque